### ISSUE TITLE
Возможное наложение вьюх

### ISSUE THREAD

**Issue by gnezdilovdenis** [Sunrizzin/SkyEngTest#2]
Получается, если n запросов выполняется n вьюх на экране

https://github.com/Sunrizzin/SkyEngTest/blob/d21a71feb944f24fe3f8a9d027b90448dcb9bf74/SkyEngUsanov/Service/SearchApiService.swift#L20

**Comment by Sunrizzin** [comment]
Спасибо! Пофиксил!
