### ISSUE TITLE
Смешение логики

### ISSUE THREAD

**Issue by gnezdilovdenis** [Sunrizzin/SkyEngTest#3]
Плохая практика в сервисы UI портировать.
https://github.com/Sunrizzin/SkyEngTest/blob/d21a71feb944f24fe3f8a9d027b90448dcb9bf74/SkyEngUsanov/Service/SearchApiService.swift#L17

**Comment by Sunrizzin** [comment]
Спасибо, но это было сделано сознательно. КРоме вас на это внимание никто не обратил

**Comment by Sunrizzin** [comment]
В любом случае - поправлю. Спасибо!
